//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptionEOD
{
    using System;
    using System.Collections.Generic;
    
    public partial class Group
    {
        public Group()
        {
            this.GroupParams = new HashSet<GroupParam>();
            this.GroupSymbols = new HashSet<GroupSymbol>();
        }
    
        public string groupName { get; set; }
        public string groupNotes { get; set; }
    
        public virtual ICollection<GroupParam> GroupParams { get; set; }
        public virtual ICollection<GroupSymbol> GroupSymbols { get; set; }
    }
}
