//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptionEOD
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionError
    {
        public string underSymbol { get; set; }
        public int tradeDate { get; set; }
        public int expYear { get; set; }
        public int expMonth { get; set; }
        public int dldAttempt { get; set; }
        public int lastAttDate { get; set; }
        public int lastAttTime { get; set; }
        public int success { get; set; }
        public string notes { get; set; }
        public string groupName { get; set; }
    }
}
