//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OptionEOD
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SymsEntities : DbContext
    {
        public SymsEntities()
            : base("name=SymsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<GroupParam> GroupParams { get; set; }
        public virtual DbSet<Group> Groups { get; set; }
        public virtual DbSet<GroupSymbol> GroupSymbols { get; set; }
    }
}
